correlation coefficients
MarkGotLasagna/DWS pull request #13
Opened 2024-05-06 12:45 UTC by RossoMalpelooo

Added coefficient based correlation (pearson, spearman, kendall). Simple code refactoring to make code more readable and reusable.

2024-05-07 04:54 UTC, MarkGotLasagna requested changes
Ho fatto alcuni commenti in diversi punti.

- [ ] Cambiami il nome di `v_crop_1` in `v_crop_01`.

- [ ] Il file `norm_plot_peaks.asv` non dovrebbe essere nella pull, come mai ci sia non lo so. Se per favore me lo rimuovi. Stranamente nella tua fork me lo da come eliminato ma non qui.
- [ ] Nel file `norm_plot_peaks.m` ho fatto un commento su una linea. Se me lo guardi e modifichi in accordo.

2024-05-07 04:54 UTC, MarkGotLasagna commented on MATLAB/kendall_plot_peaks.m
Cambiami il nome di `v_crop_1` in `v_crop_01` per favore.

2024-05-07 04:54 UTC, MarkGotLasagna commented on MATLAB/norm_plot_peaks.asv
Se mi rimuovi per favore questo file `norm_plot_peaks.asv` siccome un temporaneo salvato dall'editor e non ci serve.

2024-05-07 04:54 UTC, MarkGotLasagna commented on MATLAB/norm_plot_peaks.m
Cambiami il nome di `v_crop_1` in `v_crop_01` per favore.

2024-05-07 04:54 UTC, MarkGotLasagna commented on MATLAB/spearman_plot_peaks.m
Cambiami il nome di `v_crop_1` in `v_crop_01` per favore.

2024-05-07 04:54 UTC, MarkGotLasagna commented on MATLAB/norm_plot_peaks.m
> +    correlations_vector = correlations_matrix(:)';
Mi puoi verificare che `correlation_matrix` e `correlation_vector` siano la stessa cosa? Penso il primo dei due sia a prescindere un vettore. Se così è, chiamalo direttamente `correlation_vector`.

2024-05-11 09:57 UTC, RossoMalpelooo commented on MATLAB/norm_plot_peaks.m
> +    correlations_vector = correlations_matrix(:)';
controllo, ma non penso. se ti ricordi il prof aveva dovuto introdurre questo "trick" perché non riusciva ad ottenere un vettore in un solo passaggio, quindi generava prima una matrice e poi da quella ricavava il vettore.

2024-05-11 10:14 UTC, RossoMalpelooo commented
Ho aggiornato come mi hai chiesto. Ti confermo che avevi ragione sulle variabili `correlation_matrix` e `correlation_vector`.

2024-05-11 10:15 UTC, RossoMalpelooo commented on MATLAB/norm_plot_peaks.m
> +    correlations_vector = correlations_matrix(:)';
avevi ragione

2024-05-11 10:17 UTC, MarkGotLasagna approved these changes
Molto bene 👍

2024-05-11 10:18 UTC, merged